export const UPDATE_ACTION = 'UPDATE_ACTION'

export const ADD_SPRITE = 'ADD_SPRITE'
export const UPDATE_SPRITEACTION = 'UPDATE_SPRITEACTION'
export const DELETE_SPRITE = 'DELETE_SPRITE'
export const UPDATE_SPRITE_POS = 'UPDATE_SPRITE_POS'

export const PLAY_ACTION = 'PLAY_ACTION'
export const RESET_ACTION = 'RESET_ACTION'
export const UPDATE_MAIN_ACTION = 'UPDATE_MAIN_ACTION'